### ISSUE TITLE
Pastas não seguem padrão do Osmar

### ISSUE THREAD

**Issue by PoweredTable** [GreyPompom/sistema_emprestimo_A3#26]
O Osmar fez algumas equipes seguirem o padrão de pastas dele, inclusive nossa equipe.

Este padrão incluí:
- Nomes das pastas em português;
- Nomes das pastas em minúsculo.

Neste projeto, as pastas `view` e `model` provavelmente precisarão ser traduzidas, e a pasta `DAO` renomeada para minúsculo.

**Comment by osmarbraz** [comment]
Este padrão é meu.
É padrão da linguagem de programação.
Segue a documentação de referência.
https://www.cin.ufpe.br/~gta/rup-vc/extend.formal_resources/guidances/examples/resources/java.htm
